open module com.mastfrog.blather {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.blather;

    // derived from com.fasterxml.jackson.core/jackson-databind-2.13.2.2 in com/fasterxml/jackson/core/jackson-databind/2.13.2.2/jackson-databind-2.13.2.2.pom
    requires transitive com.fasterxml.jackson.databind;
    requires transitive com.mastfrog.acteur;
    requires transitive com.mastfrog.acteur.headers;
    requires transitive com.mastfrog.giulius;
    requires transitive com.mastfrog.giulius.tests;
    requires transitive com.mastfrog.url;
    requires transitive com.mastfrog.util.net;

    // derived from io.netty/netty-codec-http-4.1.76.Final in io/netty/netty-codec-http/4.1.76.Final/netty-codec-http-4.1.76.Final.pom
    requires transitive io.netty.netty.codec.http;

    // derived from io.netty/netty-handler-4.1.76.Final in io/netty/netty-handler/4.1.76.Final/netty-handler-4.1.76.Final.pom
    requires transitive io.netty.netty.handler;
    requires java.logging;

    // derived from junit/junit-4.13.2 in junit/junit/4.13.2/junit-4.13.2.pom
    requires transitive junit.junit;

}
